name: Generate ascii workflow

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable and run
        working-directory: .github/workflows
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh
