name: Generate ascii workflow

on: push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable and run
        working-directory: .github/workflows
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh

      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
          name: gragon-txt-file
          path: .github/workflows/dragon.txt  # <-- correct location

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: gragon-txt-file
          path: .                               # <-- put file in CWD

      - name: test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon text file
        uses: actions/download-artifact@v4
        with:
          name: gragon-txt-file
          path: .

      - name: Read File
        run: cat dragon.txt
