name: exploring Variables and Secrets
on: push

env:
  IMAGE_NAME: github-actions.nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Optional sanity checks
      - name: Show paths
        run: |
          pwd
          ls -la
          ls -la .github/workflows

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .                               # repo root
          file: .github/workflows/Dockerfile       # <-- actual Dockerfile path
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
